{
  "listen_addr": ":9200",
  "server_id": "game-1",
  "conn_read_timeout_sec": 120,
  "conn_write_timeout_sec": 120,
  "conn_keepalive_sec": 30,
  "redis": {
    "addr": "127.0.0.1:6379",
    "password": "",
    "db": 0,
    "uid_key": "player:uid",
    "pool_size": 50,
    "minIdle_conns": 5,
    "health_check_sec": 10
  }
}
