{
  "listen_addr": ":9100",
  "game_addr": "127.0.0.1:9200",
  "redis": {
    "addr": "127.0.0.1:6379",
    "password": "",
    "db": 0,
    "uid_key": "player:uid",
    "pool_size": 500,
    "minIdle_conns": 20
  }
}
